apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dev-ticker
  name: dev-ticker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dev-ticker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: dev-ticker
    spec:
      containers:
      - image: matterlabs/dev-ticker:latest
        imagePullPolicy: "Always"
        name: dev-ticker
        ports:
        - containerPort: 9876
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      # volumes: null
status: {}
