apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dev-ticker
  name: dev-ticker
spec:
  ports:
  - name: "9876"
    port: 9876
    targetPort: 9876
  selector:
    io.kompose.service: dev-ticker
status:
  loadBalancer: {}
