apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: geth
  name: geth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: geth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: geth
    spec:
      containers:
      - image: matterlabs/geth:latest
        imagePullPolicy: "Always"
        name: geth
        ports:
        - containerPort: 8545
        - containerPort: 8546
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/geth/data
          name: geth-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: geth-claim0
        persistentVolumeClaim:
          claimName: geth-claim0
status: {}
