[package]
name = "zksync"
version = "0.1.0"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
edition = "2018"

[dependencies]
models = { path = "../../core/lib/models", version = "0.0.1" }
eth_client = { path = "../../core/lib/eth_client", version = "0.1.0" }
crypto_exports = { path = "../../core/lib/crypto_exports", version = "0.1.0" }
franklin_crypto = { package = "franklin-crypto", path = "../../../franklin-crypto", version = "0.0.5" }
bellman = { package = "bellman_ce", path = "../../../bellman", version = "0.3.2" }


sha2 = "0.8"
web3 = "0.13.0"
ethabi = "9.0.0"
tokio = { version = "0.2", features = ["time"] }
futures = { version = "0.3", features = ["compat"] }

serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.0"

reqwest = { version = "0.10", features = ["json", "blocking"] }
anyhow = "1.0"
thiserror = "1.0"

jsonrpc-core = "14.0.3"

num = { version = "0.2", features = ["serde"] }

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }

[features]
integration-tests = []
