[package]
name = "tok_cli"
version = "0.1.0"
authors = ["Vlad Bochok <vladbochok1@gmail.com>"]
edition = "2018"

[dependencies]
models = { path = "../../core/lib/models", version = "0.0.1" }

anyhow = "1.0"
tokio = { version = "0.2", features = ["full"] }
web3 = "0.13.0"
serde_json = "1.0"
env_logger = "0.7"
structopt = "0.3.17"
reqwest = { version = "0.10", features = ["json"] }
jsonwebtoken = "7"
serde = "1"
url = "2"
